### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by mtoohey31** [tli-group-4-grimm/frontend#36]
- [x] #42

**Comment by ianlavine** [comment]
Rework userform.tsx to only show some fields. 
Connect userform to second page once submit is pressed.
load addons data into second page.

**Comment by RayanAlim** [comment]
Reformat search,  userform, navbar, landing page, 
Reformat dashboard
enable dark mode in dashboard 
populate car images + link it to display in search results 
@RayanAlim

**Comment by RayanAlim** [comment]
- Print Senso call in dashboard
- Have 'cart' like a component for addons selected

**Comment by RayanAlim** [comment]
- Have 'cart' like a component for addons selected

**Comment by RayanAlim** [comment]
- Reformat addons search results

**Comment by RayanAlim** [comment]
Display selected Car details in the dashboard
